Frontend:
  impl: SimpleO3
  clock_ratio: 8
  num_expected_insts: 500000
  traces: 
    - ../workloads/ramulatorv2-rh_mitigations-cputraces/cputraces/470.lbm

  Translation:
    impl: RandomTranslation
    max_addr: 2147483648
              

MemorySystem:
  impl: GenericDRAM
  clock_ratio: 3

  DRAM:
    impl: DDR4
    org:
      preset: DDR4_8Gb_x8
      channel: 1
      rank: 2
    timing:
#      preset: DDR4_3200AC
#      preset: myDDR4_ocl
#      rate: 2500
      rate: 3200
      nBL: 4
      nCL: 12
      nRCD: 10
      nRP: 10
      nRAS: 29
      nRC: 30
      nWR: 16
      nRTP: 9
      nCWL: 12
      nCCDS: 4
      nCCDL: 6
      nRRDS: 4
      nRRDL: 8
      nWTRS: 3
      nWTRL: 9
      nFAW: 34
      nRFC: 576
      nREFI: 12480
      nCS: 2
      tCK_ps: 800

  Controller:
    impl: Generic
    Scheduler:
      impl: FRFCFS
    RefreshManager:
      impl: AllBank
    RowPolicy:
      impl: ClosedRowPolicy
      cap: 4
    plugins:

  AddrMapper:
    impl: RoBaRaCoCh
